name       : libgcrypt11
version    : 1.5.3
release    : 10
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.5.3.tar.gz : 9dd2f359c16d7b8128d53f019c685cdedbcdcd1888904228a272d4769d9bf4e6
license    :
    - GPL-3.0
summary    : libgcrypt11 (Binary Compatibility Library)
builddeps  :
    - libgpg-error-devel
    - libgpg-error-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
devel      : yes
component  : binary.compat
emul32     : yes
description: |
    This package provides binary compatibility only. It is forbidden to build against it.
setup      : |
    # This package is provided to replace the Steam runtime version, as such the
    # patches are kept in sync with Ubuntu. It is forbidden to build anything against
    # this package in Solus, with *no* exceptions.
    %apply_patches
    
    %configure --with-gpg-error-prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Only ship libraries
    for i in /usr/bin /usr/share /usr/include; do
        rm -rfv "$installdir/$i"
    done
    # Forbid linking too
    rm $installdir/%libdir%/*.so
    # Skip any potential .la files
    rm -f $installdir/%libdir%/*.la || :
