name       : libgcrypt11
version    : 1.5.6
release    : 11
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.5.6.tar.gz : 5cf9a2f6bdb71c4e33895c3213a84890fe5a633d00de4f7953d2c9ab2e81998f
license    :
    - GPL-3.0
summary    : libgcrypt11 (Binary Compatibility Library)
builddeps  :
    - libgpg-error-devel
    - libgpg-error-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
devel      : yes
component  : binary.compat
emul32     : yes
description: |
    This package provides binary compatibility only. It is forbidden to build against it.
setup      : |
    %configure --with-gpg-error-prefix=/usr
build      : |
    %make
install    : |
    %make_install
    # Only ship libraries
    for i in /usr/bin /usr/share /usr/include; do
        rm -rfv "$installdir/$i"
    done
    # Forbid linking too
    rm $installdir/%libdir%/*.so
    # Skip any potential .la files
    rm -f $installdir/%libdir%/*.la || :
